theme: jekyll-theme-cayman
title: RSE Reproducibility Hackathon 02/12/2020

email: c.cave-ayland@imperial.ac.uk
description: >-
  A hackathon event focusing on reproducibility in computational research. Led
  by the Imperial College Research Software Engineering team.
twitter_username: ImperialRSE
github_username: cc-a
